import os
from app.services.dataset_generator import generate_benchmark_52k_dataset
from app.services.normalizer import LogNormalizer
from app.services.detectors import DeterministicDetectors
from app.services.gemini_narrative import GeminiNarrativeService


def test_gemini_deterministic_fallback_when_no_key():
    """Verify that GeminiNarrativeService falls back cleanly when GEMINI_API_KEY is not set."""
    os.environ["GEMINI_API_KEY"] = ""
    logs = generate_benchmark_52k_dataset()
    normalized = LogNormalizer.normalize_batch(logs)
    alerts, _ = DeterministicDetectors.analyze_logs(normalized)
    valid_ids = {log.event_id for log in logs}

    claims, meta, is_gemini_used = GeminiNarrativeService.generate_narrative(alerts, valid_ids)

    assert is_gemini_used is False
    assert meta["mode"] == "deterministic_fallback"
    assert len(claims) > 0
    assert all(c.is_verified for c in claims)


def test_gemini_citation_validation_filters_invalid_ids():
    """Verify that invalid citations generated by AI are filtered out."""
    gemini_raw_json = {
        "title": "Test Incident",
        "severity": "HIGH",
        "summary": "Test Summary",
        "steps": [
            {
                "stage": "Initial Access",
                "claim": "Valid claim with existing evidence ID",
                "evidence_ids": ["EV-10001"],
                "confidence": 0.99
            },
            {
                "stage": "Exfiltration",
                "claim": "Invalid claim with fake evidence ID",
                "evidence_ids": ["EV-FAKE-9999"],
                "confidence": 0.5
            }
        ]
    }

    valid_ids = {"EV-10001", "EV-10002", "EV-10003"}
    claims, is_valid = GeminiNarrativeService._validate_and_filter_narrative(gemini_raw_json, valid_ids)

    assert is_valid is True
    # Claim 1 should be retained and verified
    assert len(claims) == 1
    assert claims[0].claim_id == "CLM-001"
    assert claims[0].evidence_event_ids == ["EV-10001"]
    assert claims[0].is_verified is True
